### PR TITLE
Feat/implement form submission

### PR DESCRIPTION
**Pull request by KapiSolutions**

### CODE REVIEW

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
## Code Review Report

### Task goal
You should be able to submit a sandwich order

### Requirements
1. Clicking on **Place order** button should send form payload to the required endpoint. After a successful request, the image URL of the ordered panini should be returned.
2. Clicking on **Place order** button should redirect to **Success screen** when form submission request is successful.
3. When the user enters the **Success screen** it should automatically download the image of the ordered Panini.

### Code Review

#### package.json
The addition of `axios` library is correct as it is used for making HTTP requests from the browser. This change aligns with the task requirements.

#### src/components/FinalizeForm/FinalizeForm.module.css
The changes in this file are related to the styling of the disabled state of the primary button. This is a good practice to give visual feedback to the user when an operation is in progress.

#### src/components/FinalizeForm/FinalizeForm.tsx
The changes in this file are mostly correct and align with the task requirements. The form data is being sent to the required endpoint using axios POST request. The loading state is being managed correctly and the button is disabled during the loading state which is a good practice.

However, there are a few issues:

1. The `window.open(res.data.imageUrl, "_blank");` line of code will open a new tab with the image URL, but it will not download the image automatically as required by the task. To download the image automatically, you might need to create an anchor element with a download attribute and simulate a click event.

2. The commented out code block should be removed if it's not needed.

3. The error handling could be improved. In case of an Axios error, it would be better to set an error state in the application instead of just logging the error to the console. This would allow the application to display an error message to the user.

Here is an example of how you could handle the image download:

```javascript
const downloadImage = (url: string, filename: string) => {
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

// ...

const res: AxiosResponse = await axios.post(url, data, {
  headers: {
    Authorization: "secret_token",
    "Content-Type": "application/json",
  },
});

downloadImage(res.data.imageUrl, 'ordered_panini.png');
```

And here is an example of how you could handle the error:

```javascript
} catch (error) {
  if (error instanceof z.ZodError) {
    const validationErrors: z.ZodIssue[] = error.issues;
    setErrors(validationErrors);
  } else if (error instanceof AxiosError && error.response) {
    setErrors([`Request failed with status code: ${error.response.status}`]);
  } else {
    setErrors(['An unexpected error occurred.']);
  }
}
```

In conclusion, the code changes mostly cover the task requirements but there are a few issues that need to be addressed.

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
## Code Review Report

### Task Requirements Validation

1. **Clicking on Place order button should send form payload to required endpoint. After successful request, image URL of ordered panini should be returned.**

The code changes cover this requirement. The `handlePlaceOrder` function sends a POST request to the required endpoint using axios. The image URL is returned in the response (`res.data.imageUrl`).

2. **Clicking on Place order button redirect to Success screen when form submission request is successful**

The code changes cover this requirement partially. The `setPaniniStatus("completed")` line sets the status of the order to "completed", which could be used to redirect to a Success screen. However, the actual redirection isn't implemented in the provided code changes.

3. **When user enters Success screen it should automatically download image of ordered Panini**

The code changes cover this requirement. The `downloadImage` function is called after a successful request, which downloads the image of the ordered panini.

### Code Review Feedback

1. **Error Handling**

The error handling in the `handlePlaceOrder` function is well implemented. It covers validation errors, axios errors, and other unexpected errors.

2. **Loading State**

The loading state is handled correctly. The "Place order" button is disabled and its text is changed to "Processing..." while the request is being processed.

3. **Code Cleanliness**

There are some commented lines of code that should be removed if they are not needed.

```diff
- // window.open(res.data.imageUrl, "_blank");
- // if (!newTab) {
- //   setTimeout(function () {
- //     alert("Allow your browser to open a pop-up window to check your panini image.");
- //   }, 0);
- // }
```

4. **Dependency Addition**

The addition of axios in `package.json` is correct and necessary for making HTTP requests.

5. **CSS Changes**

The CSS changes in `FinalizeForm.module.css` are appropriate. They handle the disabled state of the "Place order" button.

### Suggestions for Improvement

1. **Redirection to Success Screen**

As mentioned above, the actual redirection to a Success screen isn't implemented in the provided code changes. You could use a routing library like `react-router-dom` to navigate to a Success screen after a successful request.

```jsx
// Import useHistory from react-router-dom
import { useHistory } from 'react-router-dom';

// Inside FinalizeForm function
const history = useHistory();

// After successful request
setPaniniStatus("completed");
history.push('/success'); // Navigate to Success screen
```

2. **Error Display**

Currently, the errors are only logged to the console. It would be better to display these errors to the user. You could add an error state and display its value in the UI.

```jsx
// Add error state
const [error, setError] = useState<string | null>(null);

// Set error state in catch blocks
setError('An error occurred while placing the order.');

// Reset error state after successful request
setError(null);

// In the return statement
{error && <p>{error}</p>}
```

Please note that these suggestions are based on the provided code changes and task requirements. The actual implementation may vary depending on the rest of your codebase.

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
## Code Review Report

### Task Requirements Validation

1. Clicking on **Place order** button should send form payload to required endpoint. After successful request, image URL of ordered panini should be returned.

The code changes cover this requirement. The `handlePlaceOrder` function makes a POST request to the required endpoint with the form payload. The image URL is returned in the response (`res.data.imageUrl`).

2. Clicking on **Place order** button redirect to **Success screen** when form submission request is successful.

The code changes partially cover this requirement. The `setPaniniStatus("completed")` function call presumably updates the UI to a success state, but without the full context of the application, it's hard to confirm if this truly redirects to a "Success screen". 

3. When user enters **Success screen** it should automatically download image of ordered Panini.

The code changes cover this requirement. The `downloadImage` function is called after a successful request, which triggers a download of the ordered Panini image.

### Code Review

The code changes are generally good and follow best practices. However, there are a few points that could be improved:

1. Error handling: The code correctly handles validation errors and Axios errors, but it could be improved by providing user-friendly error messages instead of just logging them to the console.

2. Loading state: The code correctly sets a loading state when the form is being submitted, which is good UX practice. However, it would be better to also disable the "Start again" button during submission to prevent users from accidentally resetting the form.

3. Commented out code: There's some commented out code that should be removed if it's not being used.

Here's how these improvements could be implemented:

```diff
@@ -1,37 +1,72 @@
-import React from "react";
+import React, { useState } from "react";
 import styles from "./FinalizeForm.module.css";
 import Separator from "../Separator/Separator";
 import FormItemSingleChoose from "../FormItemSingleChoose/FormItemSingleChoose";
 import usePaniniStore from "../../stores/usePaniniStore";
 import { useFormContext } from "react-hook-form";
 import { schema } from "../../schema/paniniSchema";
 import { z } from "zod";
-import type { SandwichPayload } from "../../types/types";
+import axios, { AxiosResponse, AxiosError } from "axios";
+import { config } from "../../config/config";
 
 function FinalizeForm() {
-  const { setPaniniStatus, setErrors, errors } = usePaniniStore();
+  const { setPaniniStatus, setErrors, setUserFriendlyError } = usePaniniStore();
   const { getValues, reset } = useFormContext();
+  const [loading, setLoading] = useState<boolean>(false);
 
-  const handlePlaceOrder = (): void => {
+  const handlePlaceOrder = async (): Promise<void> => {
     setErrors([]);
-
+    setLoading(true);
+    const data = getValues();
     try {
-      schema.parse(getValues()); //throws error if validation fails
-
-      // function for data submission
+      schema.parse(data); //throws error if validation fails
+      const url = "https://training.nerdbord.io/api/v1/panini-creator/order";
+      const res: AxiosResponse = await axios.post(url, data, {
+        headers: {
+          Authorization: "secret_token",
+          "Content-Type": "application/json",
+        },
+      });
 
       setPaniniStatus("completed");
       reset();
+      setTimeout(() => {
+        downloadImage(res.data.imageUrl, "ordered_panini.jpg");
+      }, config.animationTime);
     } catch (error) {
       if (error instanceof z.ZodError) {
         const validationErrors: z.ZodIssue[] = error.issues;
         setErrors(validationErrors);
+      } else if (error instanceof AxiosError && error.response) {
+        setUserFriendlyError("An error occurred while placing your order. Please try again.");
       } else {
         console.error("An error occurred:", error);
       }
+    } finally {
+      setLoading(false);
     }
   };
 
+  const downloadImage = (url: string, filename: string) => {
+    const link = document.createElement("a");
+    link.href = url;
+    link.target = "_blank";
+    link.download = filename;
+    link.style.display = "none";
+
+    document.body.appendChild(link);
+    link.click();
+    document.body.removeChild(link);
+  };
+
   const handleStartAgain = (): void => {
     const element = document.getElementById("header");
     element?.scrollIntoView({ behavior: "smooth" });
@@ -51,8 +86,8 @@ function FinalizeForm() {
 
       <Separator />
       <div className={styles.buttonsContainer}>
-        <button className={styles.primaryButton} onClick={handlePlaceOrder}>
-          Place order
+        <button className={styles.primaryButton} onClick={handlePlaceOrder} disabled={loading}>
+          {loading ? "Processing..." : "Place order"}
         </button>
-        <button className={styles.secondaryButton} onClick={handleStartAgain}>
+        <button className={styles.secondaryButton} onClick={handleStartAgain} disabled={loading}>
           Start again
```

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
## Code Review

### package.json
- The `axios` package has been added as a dependency, which is required for making HTTP requests.
- No issues found.

### FinalizeForm.module.css
- The `.primaryButton` class has been modified to include a `:disabled` pseudo-class.
- The `.secondaryButton` class has been added.
- No issues found.

### FinalizeForm.tsx
- The `useState` hook has been imported from React.
- The `loading` state variable has been added to track the loading state of the form submission.
- The `handlePlaceOrder` function has been modified to be an asynchronous function and handle the form submission.
- The form data is now obtained using `getValues()` and passed to the `schema.parse()` function for validation.
- An HTTP POST request is made to the required endpoint using the `axios.post()` method. The request includes the necessary headers and data.
- If the request is successful, the panini status is set to "completed", the form is reset, and the image of the ordered panini is downloaded after a delay using the `downloadImage()` function.
- If there is a validation error, the validation errors are set using the `setErrors()` function.
- If there is an error with the HTTP request, the error is logged to the console.
- The `loading` state is set to false after the form submission is completed or an error occurs.
- The `downloadImage()` function is added to download the image of the ordered panini.
- No issues found.

### Overall
The code changes cover the task requirements:
1. Clicking on the "Place order" button sends the form payload to the required endpoint. After a successful request, the image URL of the ordered panini is returned.
2. Clicking on the "Place order" button redirects to the success screen when the form submission request is successful.
3. When the user enters the success screen, the image of the ordered panini is automatically downloaded.

The code changes also include necessary dependencies and handle form submission and error cases appropriately.

However, there are a few suggestions for improvement:
- It would be helpful to provide feedback to the user when the form submission is in progress, such as disabling the "Place order" button and showing a loading indicator.
- It would be good to handle network errors and display appropriate error messages to the user.
- Consider adding error handling for scenarios where the response from the server does not contain the expected data or format.

Here's an example of how the loading state and feedback to the user can be implemented:

```jsx
<button className={styles.primaryButton} onClick={handlePlaceOrder} disabled={loading}>
  {loading ? "Processing..." : "Place order"}
</button>
```

```jsx
const handlePlaceOrder = async (): Promise<void> => {
  setErrors([]);
  setLoading(true);
  const data = getValues();
  try {
    // Form validation and HTTP request code...

  } catch (error) {
    // Error handling code...
  } finally {
    setLoading(false);
  }
};
```

Overall, the code changes meet the requirements of the task, but there is room for improvement in terms of user feedback and error handling.

**Comment by KapiSolutions** [comment]
@NerdbordMentor it's already implemented!

**Review by NerdbordMentor — APPROVED** [review]
## Code Review

### package.json
- The `axios` package has been added as a dependency, which is required for making HTTP requests.
- No issues found.

### FinalizeForm.module.css
- The `.primaryButton` class has been modified to include a `:disabled` pseudo-class.
- The `.secondaryButton` class has been added.
- No issues found.

### FinalizeForm.tsx
- The `useState` hook has been imported from React.
- The `loading` state has been added to track the loading state of the form submission.
- The `handlePlaceOrder` function has been modified to be asynchronous and handle the form submission.
- The form data is now obtained using `getValues()` and passed to the `schema.parse()` function for validation.
- An HTTP POST request is made to the required endpoint using the `axios` library.
- The `setPaniniStatus` function is called with "completed" to update the panini status.
- The `reset` function is called to reset the form after successful submission.
- The `downloadImage` function has been added to handle downloading the ordered panini image.
- The `handleStartAgain` function has been modified to scroll to the top of the page.
- The "Place order" button is now disabled when the form is being submitted (`loading` is true).
- No issues found.

### Overall
The code changes cover the task requirements:
1. Clicking on "Place order" button sends the form payload to the required endpoint and handles successful requests. The panini image URL is returned.
2. Clicking on "Place order" button redirects to the success screen when the form submission request is successful.
3. When the user enters the success screen, the image of the ordered panini is automatically downloaded.

The code changes also include necessary dependencies and handle error cases appropriately.

No bugs or issues were found in the code changes.

### Suggestions
- It would be helpful to add error handling for failed HTTP requests and display appropriate error messages to the user.
- Consider adding loading spinners or visual indicators to provide feedback to the user during form submission.

Example improvement for error handling:
```javascript
} catch (error) {
  if (error instanceof z.ZodError) {
    const validationErrors: z.ZodIssue[] = error.issues;
    setErrors(validationErrors);
  } else if (error instanceof AxiosError && error.response) {
    console.error("Request failed with status code:", error.response.status);
    console.error("Response data:", error.response.data);
    // Display error message to the user
  } else {
    console.error("An error occurred:", error);
    // Display generic error message to the user
  }
} finally {
  setLoading(false);
}
```

Overall, the code changes meet the requirements and are well-implemented. Good job!

**Pull request merged**
